version: '3.8'
services:
  web_app:
    build:
      context: .
      dockerfile: web_app_dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
  marian:
    build:
      context: .
      dockerfile: marian_dockerfile
    ports:
      - "5004:5004"
