services:
  web_app:
    build:
      context: .
      dockerfile: web_app_dockerfile
    image: azure-translate-app-web_app:latest
    container_name: web_app
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
  marian:
    build:
      context: .
      dockerfile: marian_dockerfile
    image: azure-translate-app-marian:latest
    container_name: marian
    ports:
      - "5004:5004"
